Part_01 for QSAR DATA processing

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.7)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.3 MB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 4.0 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 6.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.1-py3-none-any.whl (18 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.2.0 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.1

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

/usr/local/lib/python3.13/dist-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for Acetylcholinesterase**

In [3]:
# Target search for coronavirus
target = new_client.target

target_query = target.search('Bioactivity_01.csv')

targets = pd.DataFrame.from_dict(target_query)

targets

Empty DataFrame
Columns: []
Index: []

### **Select and retrieve bioactivity data for *H92c* (first entry)**

We will assign the fifth entry (which corresponds to the target protein, *H92c*) to the ***selected_target*** variable

In [ ]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL614576'

In [5]:
selected_target = 'CHEMBL614576' # Temporarily defining selected_target to resolve NameError
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [6]:
df = pd.DataFrame.from_dict(res)

In [7]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1782905,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
1,None,None,1782906,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.7
2,None,None,1782963,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
3,None,None,1782964,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,5.8
4,None,None,1782965,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1859,None,None,29287439,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,Not_determined,None,IC50,None,None,None,None
1860,None,None,29287440,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1861,None,None,29287441,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,Not_determined,None,IC50,None,None,None,None
1862,None,None,29287442,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1863,None,None,29287443,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [8]:
df.to_csv('H92C_01_bioactivity_data_raw.csv', index=False)

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [9]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_1832/3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1782905,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
1,None,None,1782906,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.7
2,None,None,1782963,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
3,None,None,1782964,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,5.8
4,None,None,1782965,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,None,None,29273881,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6154552,Cytotoxicity against rat H9c2 cells assessed a...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,19.0
1856,None,None,29273882,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6154552,Cytotoxicity against rat H9c2 cells assessed a...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,55.0
1860,None,None,29287440,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1862,None,None,29287442,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1863,None,None,29287443,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0

In [10]:
len(df2.canonical_smiles.unique())

1828

In [11]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1782905,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
2,None,None,1782963,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,7.5
3,None,None,1782964,[],CHEMBL855628,Growth inhibition of rat H9c2(2-1) cells by MT...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,5.8
4,None,None,1782965,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,6.6
5,None,None,1782966,[],CHEMBL855629,Growth inhibition of H9c2(2-1) cells by MTT as...,F,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,-Log IC50,None,UO_0000065,None,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,None,None,29273881,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6154552,Cytotoxicity against rat H9c2 cells assessed a...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,19.0
1856,None,None,29273882,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6154552,Cytotoxicity against rat H9c2 cells assessed a...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,55.0
1860,None,None,29287440,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1862,None,None,29287442,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0
1863,None,None,29287443,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6158509,Cytotoxicity against H9c2 cells assessed as in...,T,None,None,BAO_0000190,...,Rattus norvegicus,H9c2,10116,None,None,IC50,uM,UO_0000065,None,32.0

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [12]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL53463,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,31.62
2,CHEMBL217089,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,31.62
3,CHEMBL383964,CCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C[C@...,1584.89
4,CHEMBL384221,CCCCCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C...,251.19
5,CHEMBL214810,CCCCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C[...,1584.89
...,...,...,...
1855,CHEMBL6176884,CCOC(=O)COc1cc(OC)cc2c1[n+]([O-])c1ccccc1[n+]2...,19000.0
1856,CHEMBL6176112,COc1cc(OC(C)=O)c2c(c1)[n+]([O-])c1ccccc1[n+]2[O-],55000.0
1860,CHEMBL6177465,C=CS(=O)(=O)N1CCC[C@@H](Nc2nc(N)nc(Nc3cccc(Oc4...,32000.0
1862,CHEMBL6176872,C=CS(=O)(=O)N1CCC[C@@H](Nc2nc(N)nc(Nc3cccc(OCc...,32000.0
1863,CHEMBL1873475,C=CC(=O)N1CCC[C@@H](n2nc(-c3ccc(Oc4ccccc4)cc3)...,32000.0

Saves dataframe to CSV file

In [13]:
df3.to_csv('H92C_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [14]:
df4 = pd.read_csv('H92C_02_bioactivity_data_preprocessed.csv')

In [15]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [16]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL53463,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,31.62,active
1,CHEMBL217089,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)C[C@@](O)...,31.62,active
2,CHEMBL383964,CCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C[C@...,1584.89,intermediate
3,CHEMBL384221,CCCCCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C...,251.19,active
4,CHEMBL214810,CCCCOC(=O)N1CO[C@@H]2[C@H](C)O[C@@H](O[C@H]3C[...,1584.89,intermediate
...,...,...,...,...
1823,CHEMBL6176884,CCOC(=O)COc1cc(OC)cc2c1[n+]([O-])c1ccccc1[n+]2...,19000.00,inactive
1824,CHEMBL6176112,COc1cc(OC(C)=O)c2c(c1)[n+]([O-])c1ccccc1[n+]2[O-],55000.00,inactive
1825,CHEMBL6177465,C=CS(=O)(=O)N1CCC[C@@H](Nc2nc(N)nc(Nc3cccc(Oc4...,32000.00,inactive
1826,CHEMBL6176872,C=CS(=O)(=O)N1CCC[C@@H](Nc2nc(N)nc(Nc3cccc(OCc...,32000.00,inactive
1827,CHEMBL1873475,C=CC(=O)N1CCC[C@@H](n2nc(-c3ccc(Oc4ccccc4)cc3)...,32000.00,inactive

Saves dataframe to CSV file

In [17]:
df5.to_csv('H92C_03_bioactivity_data_curated.csv', index=False)

---